### ISSUE TITLE
Extend RUN VIEW command to display only metrics

### ISSUE THREAD

**Issue by grananda** [seqeralabs/tower-cli#100]
We need to rethink how to show the metrics. At the end it has to be some kind of table like this:
```
+--------------------------+----------+--------+-------+-------+-------+-------+--------+
|         process          |  metric  |  mean  |  min  |  q1   |  q2   |  q3   |  max   |
+--------------------------+----------+--------+-------+-------+-------+-------+--------+
| RSEQC_READDUPLICATION    | cpuUsage | 219.45 | 153.8 | 173.3 | 189.4 | 250.5 | 330.25 |
| RSEQC_JUNCTIONSATURATION | cpuUsage |  227.1 |  93.2 | 209.2 | 209.4 | 308.6 |  315.1 |
+--------------------------+----------+--------+-------+-------+-------+-------+--------+
```
So I think that it is better to remove metrics from the VIEW command and move them into a new command.

I think that it will be more useful if we move them into a subcommand like this:
```
tw runs view -i <run_id> metrics -f <filter_process> --type cpu,mem,vmem,time,reads,writes,cpuUsage,memUsage,timeUsage --columns mean,min,q1,q2,q3,max,minLabel,q1Label,q2Label,q3Label,maxLabel,warnings
```

- `-f` is optional and by default all the process are shown
- `--type` is optional and the default is `cpu,mem,time`
- `--columns` is optional and the default is `mean,min,q1,q2,q3,max`

**Comment by swampie** [comment]
Let's think about having a `*` type and columns to prevent "hidden" metrics that can come in future release of nextflow
