### ISSUE TITLE
Add the concept of visibility to the workspace creation

### ISSUE THREAD

**Issue by swampie** [seqeralabs/tower-cli#105]
Currently (https://github.com/seqeralabs/tower-cli/blob/master/src/main/java/io/seqera/tower/cli/commands/workspaces/CreateCmd.java) the workspace create command set the visibility to private.

Add a new option (visibility) which accepts PRIVATE or SHARED values and change the body accordingly: PRIVATE should be the default if the option is missing

**Comment by jordeu** [comment]
Is this a duplicate of #76 ?
