### ISSUE TITLE
Replace "create" commands with "add" 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-cli#107]
Looking at this command 

```
tw credentials create aws
```

Made me think the `create` verb is very confusing, *credentials* are not created but added to the tower config. 

I think the same concept applies to other resources. It would makes sense to replace `create` verb into `add`

**Comment by jordeu** [comment]
Ok, make sense. In fact we where mixing both https://github.com/seqeralabs/tower-cli/issues/101
