### ISSUE TITLE
Allow users to inspect (or download) the logs.reports files for a  entire workflow or a task

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/tower-cli#109]
## Feature request

The use-case is straight-forward, having the ability to download the logs for a workflow would speed up the debugging process.

In addition, since in future we are planning other features, it'd be great to have the ability to download resources in general, such as `datasets` / `reports` (the run metrics) / specific outputs etc.

**Comment by jordeu** [comment]
https://github.com/seqeralabs/tower-cli/issues/41 duplicated?

**Comment by abhi18av** [comment]
Good point!

Yes this overlaps a bit with the #45  (and this [discussion](https://github.com/seqeralabs/nf-tower-cloud/discussions/1171))  for the logs and I see that the datasets is covered by https://github.com/seqeralabs/tower-cli/issues/41 


So, I have a couple of things in mind for downloading workflow meta data, for example 

- the resolved configuration
- web reports 


If these are also tracked elsewhere, then we can close the issue. Otherwise, shall we update the title and keep as feature-request?

**Comment by jordeu** [comment]
- the resolved configuration will be included in next release: https://github.com/seqeralabs/tower-cli/issues/36
- for the web reports I've added this on hold issue: https://github.com/seqeralabs/tower-cli/issues/110

**Comment by abhi18av** [comment]
This is great - ❤️ Tower CLI!

![](https://media1.giphy.com/media/xHMIDAy1qkzNS/giphy.gif?cid=36b14facshbuhv4b36gzdklwjnbs3f04o38d2sviizfhow95&rid=giphy.gif&ct=g)
