### ISSUE TITLE
Allow the users to specify a config file, which is a counterpart to the "Advanced config" 

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/tower-cli#137]
I think it’d be great is people are able to specify the configs which they add to the `Advanced config` sections for a pipeline.

Currently it is possible via the `tw launch --config` option. 

```
$ ./tw launch
Missing required parameter: 'PIPELINE_OR_URL'

Usage: tw launch [OPTIONS] PIPELINE_OR_URL

Launch a Nextflow pipeline execution.
...

Advanced options:
      --config=<config>                    Additional Nextflow config settings can be provided in the above field. These settings will be included in the `nextflow.config` file for this execution.
...

```

However it'd be a better to have a file as an input since the config is often used for things like 

1. `name` of a pipeline `manifest.name = 'awesome-pipeline'`
2.  Tweak the settings for underlying platform CLIs like `aws.batch.maxParallelTransfers = 4`

**Comment by jordeu** [comment]
Not sure if I understand. Currently the `--config` option you need to pass a file (maybe we need to improve the description). Is this enough?

**Comment by abhi18av** [comment]
Haha, I love it when a feature request is already implemented!

Yes, tweaking the description would be great.

**Comment by jordeu** [comment]
Nice, I'll keep this open until we fix the description.

**Comment by abhi18av** [comment]
Thanks for looking into this Jordi :)
