### ISSUE TITLE
Manage workspaces

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#14]
Allow to manage workspaces from CLI

Example usage:
```
towr workspaces create -n <myWorkspace> ...
towr workspaces delete -n <myWorkspace> 
towr workspaces update -n <myWorkspace> ...
towr workspaces leave -n <myWorkspace>
towr workspaces list ...
```

**Comment by grananda** [comment]
@jordeu should be left participant-related actions implementations for a participant's command instead?

**Comment by jordeu** [comment]
> @jordeu should be left participant-related actions implementations for a participant's command instead?

This I'm not sure what will be the best way to manage them from the CLI. I think that it needs a bit of discussion first, so maybe we can close this issue without participants.

**Comment by grananda** [comment]
I agree. Getting test to run in binary, after that all good for review. Thanks
