### ISSUE TITLE
[proposal] General ID vs name usage at CLI

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#142]
# Description

Many resources can be identified by a unique ID or by a name (within a workspace or organization scope). This proposal wants to define a long term solution to how to use them at the CLI. Some resources have the problem that the current API do not have any endpoint to query them by name, to use them currently we need to request the full list and search them locally. 

## The workspace

Can be identified using a `long` id or with unique `workspace name` + `organization name`.

Proposal:
- At `workspaces` subcommands use `-n`/`--name` for the workspace name, `-o`/`--organization` for organization name and `-i`/`--id` for ID. **Do not use the `TOWER_WORKSPACE_ID` env variable here**.
- If there is only one organization the option `-o`/`--organization` will be optional.
  
- At other subcommands use always `-w`/`--workspace` optional option to pass the `id` or to pass the name `organization_name/workspace_name`. We can use the `/` to detect that is a name. 
  The `TOWER_WORKSPACE_ID` will be used if available. Issue: https://github.com/seqeralabs/tower-cli/issues/63
  
Examples:
```
tw workspaces delete -i <WORKSPACE_ID> 
tw workspaces view --id <WORKSPACE_ID>
tw workspaces add -n <WORKSPACE_NAME>           (only name is available on insertion)
tw workspaces update --name <WORKSPACE_NAME> 


tw compute-envs ... -w <WORKSPACE_NAME_OR_ID>
tw actions ... -w <WORKSPACE_NAME_OR_ID>
tw credentials ... -w <WORKSPACE_NAME_OR_ID>
tw participants ... -w <WORKSPACE_NAME_OR_ID>
tw pipelines ... -w <WORKSPACE_NAME_OR_ID>
tw runs ... -w <WORKSPACE_NAME_OR_ID>

```

## Organization

Can be identified using a `long` id or with unique name. Notice that an organization name with only digits is not valid.

Proposal:
- At `organizations` subcommands use `-n`/`--name` for the name and `-i`/`--id` for ID. **Do not use the TOWER_WORKSPACE_ID env variable here.**
  
- At other subcomands use always optional option `-o`/`--organization` that accepts both things. We can use the fact that the id is only digits to detect id vs name.

Examples:
```
tw organizations view -i <ORG_ID>
tw organizations delete --name <ORG_NAME>
tw organizations add -n <ORG_NAME>           (only name is available on insertion)
tw organizations update --id <ORG_ID>

tw members ... -o <ORG_NAME_OR_ID>
tw teams ... -o <ORG_NAME_OR_ID>
tw collaborators ... -o <ORG_NAME_OR_ID>  
```

## Pipelines

Can be identified using a `long` or a unique name at the organization level. Notice that a pipeline name with only digits is not valid.

Proposal:
- At `pipelines` subcommands use `-n`/`--name` for the name and `-i`/`--id` for ID.
  
- Only the `tw launch` uses the pipeline and it's a special command. Here we'll keep using the positional parameter that accepts the name of the pipeline or a Nextflow URL repo. 

Examples:
```
tw pipelines delete -i <PIPE_ID>
tw pipelines export --id <PIPE_ID>
tw pipelines import -n <PIPE_NAME>        (only name is available on insertion)
tw pipelines add --name <PIPE_NAME>        (only name is available on insertion)
tw pipelines update -n <PIPE_NAME> 
tw pipelines view -i <PIPE_ID>

tw launch <PIPELINE_NAME>
tw launch <PIPELINE_ID>         (do we want to accept this? theorically is possible to automatically detect this case)
```

## Runs

Can be identified using a random string ID. It is only used at `runs` subcommands.

Proposal:
- At `runs` subcommands use `-i`/`--id` for ID

Examples:
```
tw runs view -i <RUN_ID>
tw runs relaunch --id <RUN_ID>
```

## Actions

Can be identified using a random string ID and a unique name (at workspace scope). It is only used at `actions` subcommands.

Proposal:
- At `actions` subcommands use `-n`/`--name` for the name and `-i`/`--id` for ID.
 

## Compute Environments

Can be identified using a random string ID and a unique name (at workspace scope).

Proposal:
- At `compute-envs` subcommands use `-n`/`--name` for the name and `-i`/`--id` for ID.

- At other commands use `-c`/`--compute-env` that accepts both things. First check if the name exists, if not use it as an ID.

Examples:
```
tw compute-envs view -i <CE_ID>
tw compute-envs import -n <CE_NAME> ...

tw runs relaunch --compute-env <CE_ID> ...
tw launch -c <CE_NAME> ...
```

## Credentials

Can be identified using a random string ID and a unique name (at workspace scope).

Proposal:
- At `credentials` subcommands use `-n`/`--name` for the name and `-i`/`--id` for ID.

- At other commands use `-c`/`--credentials` that accept both things. First check if the name exists, if not use it as an ID.

Examples:
```
tw credentials add aws -n <CREDS_NAME>

tw credentials delete -i <CREDS_ID>

tw compute-envs add gke -c <CREDS_ID>
tw compute-envs add gke --credentials=<CREDS_NAME>
```

Related issues:
https://github.com/seqeralabs/tower-cli/issues/88
https://github.com/seqeralabs/tower-cli/issues/63

**Comment by grananda** [comment]
Thanks @jordeu (@swampie ) and sorry, I did not read until now. Will follow the instructions when I retake the issue.

**Comment by grananda** [comment]
Just to have it clear, and as a general rule, we will be using a `name` or `ID` convention for resource referencing here; meaning I can reference a CE by `name` or `ID`.

**Comment by grananda** [comment]
When name and id are both strings, search first by ID (credentials and CE)
