### ISSUE TITLE
Colours 🌈 🌟 

### ISSUE THREAD

**Issue by ewels** [seqeralabs/tower-cli#148]
I'm a big fan of colours in the terminal, I find it makes outputs much easier to read.

I wonder if some of the tower cli outputs could be improved with a dash of colour. For example, highlighting statuses and varying column colours a little when listing runs would make it much easier to scan:

![image](https://user-images.githubusercontent.com/465550/142436390-6828b9b1-b620-4c08-9555-5fa41fd1e9dc.png)

We try to do this with the @nf-core helper tools. We're in Python and I use the `rich` library, which also allows having URLs linked to from text. For example, cmd+clicking the pipeline name in this output links to the webpage for that pipeline:

![image](https://user-images.githubusercontent.com/465550/142436605-fea5f88a-2aed-4f91-9788-4554398a063f.png)

**Comment by pditommaso** [comment]
Love this, tho don't think there's Rich equivalent for Jv world :(

**Comment by jordeu** [comment]
Yes, we can add [colors](https://picocli.info/#_more_colors) easily!

 For example at `info` we are using them:

![Screenshot from 2021-11-18 16-08-33](https://user-images.githubusercontent.com/1315429/142441913-318d764d-a93f-4e44-9801-6366ad1078ae.png)

I guess that this `status` column is a good candidate to start on.

**Comment by pditommaso** [comment]
![](https://media0.giphy.com/media/PUBxelwT57jsQ/giphy.gif)

**Comment by ewels** [comment]
Awesome 👏🏻 

Yeah status seems the obvious one, that would help a lot 😊 Linking to the web ui would also be ace if that's possible (eg. https://www.willmcgugan.com/blog/tech/post/real-working-hyperlinks-in-the-terminal-with-rich/ )

**Comment by jordeu** [comment]
This was so cool that I couldn't resist to give it a try:

![Screenshot from 2021-11-20 16-54-53](https://user-images.githubusercontent.com/1315429/142732795-82a1b3ae-cb09-4012-b750-1f117af08fc2.png)

**Comment by ewels** [comment]
![image](https://user-images.githubusercontent.com/465550/142741038-045b49f7-ad42-47b5-946c-93e45be5c266.jpeg)

**Comment by pditommaso** [comment]
That's very nice, tho a few things to e taken in consideration 

1. colour adds a lot of ANSI escape codes garbage in CI/automation logs, which is an important use case for the CLI tool
2. I guess the same problem when changing `tw` with sed/grep/awk/etc or these tools are smart enough to filter away ansi codes? 
3. if we go for colour we should apply consistently, not just here and there
4. colour should be configurable, maybe adding a `colour-text` or `ansi-text` choice to `--output` option  
5. as for the above I would consider this as a non-goal for short-term release

**Comment by jordeu** [comment]
- **1 & 2**: `picocli` automatically detects if ANSI is supported. I guess that no ANSI code goes to logs or into a bash pipe. I'll do some tests to verify this point.
- **3**: The pull request it's not finished (still a draft). At the PR description I've listed all the places colours and links that must be implemented to be consistent before releasing this.
- **4**: In my opinion if the `picocli` auto-detection works correctly I'll go to show colours when possible. Still `picocli` has ways to force enable or disable it using environment variables: https://picocli.info/#_heuristics_for_enabling_ansi
- **5**: Agree, that until the PR is not finished and we test points 1 and 2, this shouldn't go into a release.

**Comment by jordeu** [comment]
- **4**: Also I like the idea to add a `--no-ansi`  global flag to disable it from the command line.

**Comment by ewels** [comment]
Yeah, `rich` also [autodetects this](https://github.com/willmcgugan/rich/blob/ba5d0c2cfc35e929022dbe26c2edb4c210cb11ee/rich/console.py#L896-L913) using [`isatty`](https://man7.org/linux/man-pages/man3/isatty.3.html). Seems to work pretty well - only exception is when you _want_ colours in GItHub actions but they're not shown by default (but then you can force them on with an environment variable). Picocli approach sounds very comparable 👍🏻

**Comment by ewels** [comment]
So excited to try this out 🤗
