### ISSUE TITLE
[proposal] Allow user-specified --name for tw launch command

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#150]
At the moment it isn't possible to provide a `--name` parameter to the `tw launch` parameter because the launch id is tracked internally. If we run `tw runs list` then you can see a `Run Name` in the tabular output (as shown below) but that is randomly assigned by NF at run-time. However, this can be overwritten via `nextflow run -name <MY_NAME>`.
```
  Pipeline runs at [org / test ] workspace:

     ID             | Status    | Project Name                          | Run Name               | Username      | Submit Date                   
    ----------------+-----------+---------------------------------------+------------------------+---------------+-------------------------------
     2kcht7kGLfXXXX | SUCCEEDED | nf-core/fetchngs                      | gloomy_roentgen        | drpatelhh     | Thu, 18 Nov 2021 14:22:09 GMT 
     3IjYgpDCG8XXGa | CANCELLED | nf-core/fetchngs                      | elated_hawking         | drpatelhh     | Thu, 18 Nov 2021 14:18:27 GMT 
     4MBcnTTQXXbiMZ | FAILED    | nf-core/fetchngs                      | backstabbing_payne     | drpatelhh     | Thu, 18 Nov 2021 13:51:15 GMT 
```

I propose that we have an explicit `tw launch --name` parameter (with the appropriate validation for format and existence) that overwrites the `-name` parameter provided to NF. This would be very useful when using the CLI to come up with user-specified run names that can be propagated through subsequent `tw` commands without having to look for the appropriate identifier.

**Comment by pditommaso** [comment]
This is not trivial becuase introduces a new concept *Project Name* that currently does not exists

**Comment by drpatelh** [comment]
This proposal is to change the `Run Name` and not the `Project Name`? So for example replacing `gloomy_roentgen` in the table above with `my_custom_run_name`.

**Comment by pditommaso** [comment]
I see, there's a similar need on Tower as well.

**Comment by jordeu** [comment]
Duplicated #200
