### ISSUE TITLE
Error when (re)adding a non-existent pipeline to a workspace

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#151]
```cosole
$ tw pipelines list --workspace ***

  Pipelines at [org / test] workspace:

     ID               | Repository                                               | Description                                       
    ------------------+----------------------------------------------------------+---------------------------------------------------
     gatk4            | https://github.com/seqeralabs/gatk4-germline-snps-indels |                                                   
     nf-core_fetchngs | https://github.com/nf-core/fetchngs                      | Vanilla version of the nf-core/fetchngs pipeline. 
```

I am trying to add the nf-core/rnaseq pipeline to a workspace which doesn't exist in the output above but I get the error below:

```console
$ tw pipelines add --name=nf-core_rnaseq --workspace *** --compute-env=my-ce "https://github.com/nf-core/rnaseq"

  ERROR: A pipeline with name 'nf-core_rnaseq' already exists
```

A pipeline called `nf-core_rnaseq` did exist in this workspace previously but it was deleted. I wonder if this is cached somehow and is causing the error above?

```console
$ tw runs list --workspace ***

  Pipeline runs at [seqeralabs / testing] workspace:

     ID             | Status    | Project Name                          | Run Name               | Username      | Submit Date                   
    ----------------+-----------+---------------------------------------+------------------------+---------------+-------------------------------
     2kcht7kGLXX0XX | SUCCEEDED | nf-core/fetchngs                      | gloomy_roentgen        | drpatelhh     | Thu, 18 Nov 2021 14:22:09 GMT 
     LqsMjfcXX8xBV  | SUCCEEDED | nf-core/rnaseq                        | irreverent_shaw        | drpatelhh     | Mon, 27 Sep 2021 14:44:32 GMT 
     21hGWXXbpsrdUH | SUCCEEDED | nf-core/rnaseq                        | crazy_torricelli       | graham-wright | Wed, 22 Sep 2021 15:18:17 GMT 
```

**Comment by tcrespog** [comment]
Pipeline names are unique within all workspaces of the same org. In all likelihood, there's already a pipeline with that name in another workspace of the `seqeralabs` org.

**Comment by drpatelh** [comment]
I have checked through the workspaces that I have been added to in `seqeralabs` and we do have the nf-core/rnaseq pipeline in a couple of other places but not with exactly the same name. So it may be in a workspace I haven't been added to yet - would need someone with superpowers to confirm.

> Pipeline names are unique within all workspaces of the same org. 
We should improve the error message if this is the case.

```
ERROR: A pipeline with name 'nf-core_rnaseq' already exists in your organization
```

**Comment by tcrespog** [comment]
> So it may be in a workspace I haven't been added to yet

Could be. A deleted workspace it's also a possibility.

> We should improve the error message if this is the case.

This has been recently done. Not yet published though: https://github.com/seqeralabs/nf-tower-cloud/issues/2254.

**Comment by pditommaso** [comment]
Think #2254 is already online, indeed the above error message is the one we changed

**Comment by drpatelh** [comment]
@pditommaso I only have access to 4 workspaces in the `seqeralabs` organization. Are there any others? And if so, are you able to quickly scan through them to see if a pipeline with the name `nf-core_rnaseq` exists in the Launch pad? If it does then we can close this issue.

**Comment by pditommaso** [comment]
For reference, it already exists in the `storage-benchmarks` workspace
