### ISSUE TITLE
Launch command should only allow repository URL

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-cli#156]
Currently `tw launch` command allow the of GitHub hosted pipelines either using Git URL and short names e.g. `nextflow-io/rnaseq` . 

The latter form can be confusing with the pipelines names defined in Tower launch. 

Think `launch` should only allow fully qualified Git URLs

**Comment by pditommaso** [comment]
it would be nice to include this in the upcoming release

**Comment by jordeu** [comment]
Does Nextflow only accept `https://...` and `http://...` URLs? or there are other schemas also supported?

**Comment by pditommaso** [comment]
yes, only http(s)
