### ISSUE TITLE
Use --profile or --profiles consistently as a parameter

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#160]
`tw launch` uses `--profile`
https://github.com/seqeralabs/tower-cli/blob/e0c200f1f5fe82fafdbb5a1cb87db4dc351429bb/src/main/java/io/seqera/tower/cli/commands/LaunchesCmd.java#L60-L61

`tw pipelines` uses `---profiles`
https://github.com/seqeralabs/tower-cli/blob/e0c200f1f5fe82fafdbb5a1cb87db4dc351429bb/src/main/java/io/seqera/tower/cli/commands/pipelines/LaunchOptions.java#L27-L28

WIll also need to update step 4 in the [README](https://github.com/seqeralabs/tower-cli#launch-examples) if we go with `--profiles` which I think is the better naming convention.

**Comment by jordeu** [comment]
Given that Nextflow uses `profile` (`nextflow run -profile ...`), maybe it's better to stick to `--profile` all of them.
