### ISSUE TITLE
Add versioning + commit in the build stamp 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-cli#17]
The version should be stored into the VERSION text field in the project root. Semantic version is a good candidate 

The commit id can be retrieved using this snippet 

https://github.com/seqeralabs/nf-tower-cloud/blob/fd47eb6642983207630465ef3307d8699add8784/build.gradle#L12-L16

**Comment by jordeu** [comment]
This was already done https://github.com/seqeralabs/tower-cli/commit/12abc0ca24084b28279e1fd0fc4f2bf1ded4e5c4
