### ISSUE TITLE
Healthcheck command

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#18]
Add a command `towr healthcheck` that checks:

1. Check that the tower server URL is valid and reachable
2. Check, using the `service-info` endpoint, that the API is compatible with current CLI (see https://github.com/seqeralabs/nf-tower-cloud/issues/2029)
3. Check that  the provided token is valid and we can authenticate.

On any error/problem return a non-zero exit code.

**Comment by grananda** [comment]
@jorde what would be a compatible API version criteria for the CLI? Do we have the required API version somewhere in the CLI  tool (such as an env var)?
