### ISSUE TITLE
Connection error misleading

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/tower-cli#187]
I encountered this error today while doing development work (see screenshot). 

The filepath I was specifying for the source file was incorrect (one folder too many). The error that was returned had me confused for about five minutes until I figured this out, particularly given that the very next command to list datasets in the Workspace showed the dataset I had just created.

It wasn't until I went into the the `tower.nf` GUI and saw the  **Data** field in an infinite spinning load attempt that I clued in where the problem lay.

![image](https://user-images.githubusercontent.com/1309341/148314674-d2730f2c-4fe0-45b6-a733-3da4c7b5b335.png)

**Comment by jordeu** [comment]
Thanks for reporting.
