### ISSUE TITLE
Provide cleaner way to programmatically retrieve identifiers

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/tower-cli#188]
I am invoking the `tw` CLI via a Python script to do stuff like:
* Create datasets
* Invoke pipelines, passing in the id of the newly-created dataset identifier

The `tw` utility makes it really easy to make API calls but returns its results as a string which intermingles prose with object identifiers. Examples:
* `"\n  Dataset 'samplesheet_full' added at 34830707738561 workspace with id '7ggNFQHFxFjjJolIvX82lw'\n\n"`
* `\n  Dataset URL\n\n  -----------\n\n  https://api.tower.nf/workspaces/34830707738561/datasets/7ggNFQHFxFjjJolIvX82lw/v/1/n/samplesheet_full.csv\n`

In each case, I have to write custom (and creaky) logic to extract the identifiers I need to pass into my next command.

I suggest adding the option to have data returned in JSON format, with identifiers cleanly packaged in their own keys.

**Comment by jordeu** [comment]
All the commands have the option `-o / --output` to show the output as JSON.

```
$ tw -h

Usage: tw [OPTIONS] [COMMAND]

Nextflow Tower CLI.

Options:
  -t, --access-token=<token>   Tower personal access token (TOWER_ACCESS_TOKEN).
  -u, --url=<url>              Tower server API endpoint URL (TOWER_API_ENDPOINT) [default: 'tower.nf'].
  -o, --output=<output>        Show output in defined format (only the 'json' option is available at the moment).
  -v, --verbose                Show HTTP request/response logs at stderr.
      --insecure               Explicitly allow to connect to a non-SSL secured Tower server (this is not recommended).
  -h, --help                   Show this help message and exit.
  -V, --version                Print version information and exit.
```

Example:
```
$ tw -o json compute-envs list
{
  "workspaceRef" : "user",
  "computeEnvs" : [ {
    "id" : "4gryZ2eFPxWZCMSUUhx0i4",
    "name" : "aws_copy",
    "platform" : "aws-batch",
    "status" : "AVAILABLE",
    "lastUsed" : "2021-12-19T08:36:18Z",
    "primary" : true
  } ]
}
```

We still need to review further the JSON outputs of all the commands before releasing version 1.0. Feel free to open command specific issues if you find bugs or possible improvements, this will be really welcome.

**Comment by gwright99** [comment]
ah perfect. that simplifies things then - thanks!

**Comment by gwright99** [comment]
For future reference in case anyone else opens this ticket looking for an answer, the `-o json` MUST be defined between `tw` and the desired command.

E.g. 
```bash
$ tw -o json datasets add --workspace=34830707738561 --name grahamtest --descrip
tion="ipsem lorem" /tmp/s3files/samplesheet_full.csv
{
  "datasetName" : "grahamtest",
  "workspaceRef" : "34830707738561",
  "datasetId" : "4DH8RqF1roqMor0sjZN148"
}
```
