### ISSUE TITLE
Run view not working?

### ISSUE THREAD

**Issue by rolivella** [seqeralabs/tower-cli#195]
Hi all, I'm new to Nextflow Tower CLI. I'm testing it and it's very cool! I'm wondering how to get detailed info af a run. I've tried: 

`tw runs view --id=1R5EyNgnXGTxXGbut` 

but I get 

`ERROR: Missing the required parameter 'launchId' when calling describeLaunch`

Is this a bug? Thanks!

**Comment by jordeu** [comment]
Yes, it is. Thanks for reporting.

**Comment by jordeu** [comment]
@rolivella  new release v0.5.1 fixing this issue
