### ISSUE TITLE
How to add a local git repository to workspace using cli

### ISSUE THREAD

**Issue by prmac** [seqeralabs/tower-cli#203]
I would like to add a local git repo to tower using the cli.  What is the appropriate syntax?

**Comment by gwright99** [comment]
Hi @prmac,

You could please elaborate a bit more on the scenario you are trying to implement? 

Is it something like you have a Nextflow workflow in a git repository on your local machine and you would like Tower to be able to use it?

Best regards,
Graham

**Comment by prmac** [comment]
Hi, I have a git repo on my local machine that I want to add to launchpad on Tower.

**Comment by gwright99** [comment]
Hi @prmac - that use case is not supported at the moment. 

Your git repo needs to be on a remote server (it can be public or private). Tower can then pull the workflow from there.  

Please see [https://help.tower.nf/22.1/git/overview/](https://help.tower.nf/22.1/git/overview/) for more details on this integration.

**Comment by prmac** [comment]
Thanks Graham
