### ISSUE TITLE
Unable to launch pipeline directly

### ISSUE THREAD

**Issue by prmac** [seqeralabs/tower-cli#206]
According to [section 12 of the README](https://github.com/seqeralabs/tower-cli/blob/master/README.md#12-launch-a-pipeline-directly), I should be able to launch a pipeline directly using eg.

```tw launch nextflow-io/hello```

However, this results in the following error

`ERROR: Pipeline 'nextflow-io/hello' not found on this workspace.`

**Comment by gwright99** [comment]
Thank you for the feedback, @prmac - we'll review this issue and update our documentation as necessary.

Were you able to execute your pipeline using the full URL to the Repository? I encountered the same problem as you when using the short name, but invoked successfully when using the full path.

**Comment by jordeu** [comment]
Hi @prmac, this is an error at our documentation. Full URL needs to be used when launching pipelines not defined at Tower workspace.
