### ISSUE TITLE
tower-cli monitor command giving garbage value when running job verbosity is 3 or higher 

### ISSUE THREAD

**Issue by TSKushal** [seqeralabs/tower-cli#237]
Hi, I am trying to run a job with verbosity 3 but when I monitor the job from putty console, it is throwing garbage values as showing in below screenshot. We are not seeing the same behavior with verbosity 2. We tried with different VMs and different RAM. Could you please help me with this?

<img width="946" alt="tower-cli garbage output" src="https://user-images.githubusercontent.com/44438079/178479879-8d8c9e48-fefa-47e7-ac6a-ec1203764b8f.PNG">

**Comment by jordeu** [comment]
Not sure that I understand your question. Are you talking about the `tw` command?

**Comment by jordeu** [comment]
Seems not related to the Tower CLI

**Comment by TSKushal** [comment]
Sorry for the late reply. We actually use the "tower-cli" command not the "tw" command.
