### ISSUE TITLE
Pre-run script with cli vs tower web

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/tower-cli#238]
I have been playing around with submitting pipelines via both our Tower Enterprise deployment and the CLI (version 0.6.2).

In the Tower Compute Environment, I added a couple of lines for the pre-run script, and the pipeline ran fine.

However, when attempting to run the same pipeline with the CLI, the pre-run script from the compute environment was ignored, so that I had to specify its contents via a new pre-run script:
```
tw launch marco-test-pipeline-setonix --pre-run=/home/mdelapierre/bin/tower-prerun.sh
```

Any clue on why this is the case? Thanks,

**Comment by marcodelapierre** [comment]
Thanks @jordeu ! 
Do you have a tentative ETA for when the next tw-cli version with this bugfix will be officially released here on github?

**Comment by jordeu** [comment]
This will be part of v0.7.0 release that should be available at the end of the week.

**Comment by marcodelapierre** [comment]
Thanks for sharing the info :-)

**Comment by marcodelapierre** [comment]
FYI just added the latest version of tower-agent and tower-cli to the Spack recipes:  https://github.com/spack/spack/pull/33545

**Comment by jordeu** [comment]
Ey, very nice @marcodelapierre. Thanks!
