### ISSUE TITLE
Version 0.6.4 segfaults on ubuntu 22.04

### ISSUE THREAD

**Issue by afonsoguerra** [seqeralabs/tower-cli#247]
Running tw runs list elicits a segfault on ubuntu. 

[ [ SubstrateSegfaultHandler caught a segfault in thread 0x0000000006030a40 ] ]
siginfo: si_signo: 11, si_code: 1, si_addr: 0x00000000000000e5

General purpose register values:
  RAX 0x0000000000000072 is an unknown value
  RBX 0x00007ffdfa891fe0 points into the stack for thread 0x0000000006030a40
  RCX 0x0000000000000000 
  RDX 0x0000000000000072 is an unknown value
  RBP 0x0000000006030de0 is an unknown value
  RSI 0x00007f3ea2300481 is an unknown value
  RDI 0x0000000006030de1 is an unknown value
  RSP 0x00007ffdfa891f90 points into the stack for thread 0x0000000006030a40
  R8  0x0000000006030de0 is an unknown value
  R9  0x0000000000000000 
  R10 0x0000000000000077 is an unknown value
  R11 0x0000000000000246 is an unknown value
  R12 0x00000000060311df is an unknown value
  R13 0x0000000000000400 is an unknown value
  R14 0x0000000006030de0 is an unknown value
  R15 0x00007f3ea23002a0 is an unknown value
  EFL 0x0000000000010246 is an unknown value
  RIP 0x00007f3e9b92cef4 is an unknown value
  
Printing Instructions (ip=0x00007f3e9b92cef4):
  0x00007f3e9b92ced4: 0x41 0x80 0x3c 0x24 0xff 0x0f 0x85 0xb4 0x00 0x00 0x00 0x48 0x8b 0x05 0x12 0x3f
  0x00007f3e9b92cee4: 0x0c 0x00 0x49 0x0f 0xbe 0x16 0x4c 0x89 0xf5 0x64 0x48 0x8b 0x08 0x48 0x89 0xd0
  0x00007f3e9b92cef4: 0xf6 0x44 0x51 0x01 0x20 0x74 0x18 0x0f 0x1f 0x44 0x00 0x00 0x48 0x0f 0xbe 0x55
  0x00007f3e9b92cf04: 0x01 0x48 0x83 0xc5 0x01 0x48 0x89 0xd0 0xf6 0x44 0x51 0x01 0x20 0x75 0xed 0x84

Top of stack (sp=0x00007ffdfa891f90):
  0x00007ffdfa891f90: 0x0000000006030d60 0x00000000045cbd20
  0x00007ffdfa891fa0: 0x00007f3ea23002a0 0x000000000601d870
  0x00007ffdfa891fb0: 0x0000000000000400 0x0000000000000400
  0x00007ffdfa891fc0: 0x0000000006030de0 0x00007f3e9b932b92
  0x00007ffdfa891fd0: 0x00007ffdfa891fe0 0x00000000000003e8
  0x00007ffdfa891fe0: 0x0000000000000000 0x0a0f8a2f47f89700
  0x00007ffdfa891ff0: 0x0000000001ef2254 0x00000000000003e8
  0x00007ffdfa892000: 0x0000000000000400 0x00000000045cbd20
  0x00007ffdfa892010: 0x00000000000003e8 0x0000000006030de0
  0x00007ffdfa892020: 0x000000000601d870 0x0000000001e40ee3
  0x00007ffdfa892030: 0xffffffffffffffb0 0x0000000000000000
  0x00007ffdfa892040: 0x0000000000000000 0x00007ffdfa8920b0
  0x00007ffdfa892050: 0x00007f3ea0a42ab8 0x000000000601ec70
  0x00007ffdfa892060: 0x00007f3e9b932b10 0x0a0f8a2f47f89700
  0x00007ffdfa892070: 0x00000000c0001000 0x00000000000003e8
  0x00007ffdfa892080: 0x00000000045cbd20 0x0000000000000400
  0x00007ffdfa892090: 0x00007ffdfa8920b0 0x00007f3ea2600000
  0x00007ffdfa8920a0: 0x0000000006030a40 0x0000000001e40c6b
  0x00007ffdfa8920b0: 0x00007f3ea2fd1428 0x0a0f8a2f47f89700
  0x00007ffdfa8920c0: 0x00007f3ea419ba38 0x00007f3ea0a429a0
  0x00007ffdfa8920d0: 0x00000000006bf6af 0x00007ffdfa892100
  0x00007ffdfa8920e0: 0x00007f3ea2600000 0x00000000006bf6c2
  0x00007ffdfa8920f0: 0x00007f3ea3e69150 0x00000000012f9970
  0x00007ffdfa892100: 0x00000000006bf6af 0x00007ffdfa8920f0
  0x00007ffdfa892110: 0x0000000000000000 0x00007f3ea2c5fb58
  0x00007ffdfa892120: 0x1184f8a6a2c5fb58 0x00000000006afb26
  0x00007ffdfa892130: 0x00007f3ea2c36af8 0x00007f3ea3e0e098
  0x00007ffdfa892140: 0x000000000180e098 0x00000000006b01bf
  0x00007ffdfa892150: 0x0000000000000000 0x0000000001346a70
  0x00007ffdfa892160: 0x00007f3ea2b9b5c0 0x00007f3ea3e0e1f8
  0x00007ffdfa892170: 0x00007f3ea3e69198 0x00007f3ea2c5fb58
  0x00007ffdfa892180: 0x00007f3ea3e0e098 0x00000000006afe9d

Top frame info:
  Does not look like a Java Frame. Use JavaFrameAnchors to find LastJavaSP:
  Found matching Anchor:0x00007ffdfa892100
  LastJavaSP 0x00007ffdfa8920f0
  LastJavaIP 0x00000000006bf6af
  
Threads:
  0x0000000006030a40 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "main" - 0x00007f3ea37fff48, stack(0x00007ffdfa095000,0x00007ffdfa893000)
  
VM thread locals for the failing thread 0x0000000006030a40:
  0 (8 bytes): JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    0x0000000006030a40: 0x00007f3ea2f16010
  8 (8 bytes): StackOverflowCheckImpl.stackBoundaryTL = (Word) 1 (0x0000000000000001)
  16 (4 bytes): Safepoint.safepointRequested = (int) 2135573627 (0x7f4a447b)
  20 (4 bytes): StatusSupport.statusTL = (int) 1 (0x00000001)
  24 (32 bytes): ThreadLocalAllocation.regularTLAB = (bytes) 
    0x0000000006030a58: 0x00007f3ea0a00000 0x00007f3ea0b00000
    0x0000000006030a68: 0x00007f3ea0a42e48 0x0000000000000000
  56 (8 bytes): JavaThreads.currentThread = (Object) java.lang.Thread (0x00007f3ea37fff48)
  64 (8 bytes): JavaFrameAnchors.lastAnchor = (Word) 140728806744320 (0x00007ffdfa892100)
  72 (8 bytes): ExceptionUnwind.currentException = (Object) null
  80 (8 bytes): IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) java.util.SplittableRandom (0x00007f3ea2401a90)
  88 (8 bytes): IsolatedCompileClient.currentClient = (Object) null
  96 (8 bytes): IsolatedCompileContext.currentContext = (Object) null
  104 (8 bytes): JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles (0x00007f3ea2401ab8)
  112 (8 bytes): JNIThreadLocalPendingException.pendingException = (Object) null
  120 (8 bytes): JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  128 (8 bytes): JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  136 (8 bytes): NoAllocationVerifier.openVerifiers = (Object) null
  144 (8 bytes): ThreadingSupportImpl.activeTimer = (Object) null
  152 (8 bytes): SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes) 
    0x0000000006030ad8: 0x0000000000000000
  160 (8 bytes): VMThreads.IsolateTL = (Word) 139906988900352 (0x00007f3ea2600000)
  168 (8 bytes): VMThreads.OSThreadHandleTL = (Word) 100784320 (0x000000000601d8c0)
  176 (8 bytes): VMThreads.OSThreadIdTL = (Word) 100784320 (0x000000000601d8c0)
  184 (8 bytes): VMThreads.StackBase = (Word) 140728806748160 (0x00007ffdfa893000)
  192 (8 bytes): VMThreads.StackEnd = (Word) 140728798367744 (0x00007ffdfa095000)
  200 (8 bytes): VMThreads.nextTL = (Word) 0 (0x0000000000000000)
  208 (8 bytes): VMThreads.unalignedIsolateThreadMemoryTL = (Word) 100862528 (0x0000000006030a40)
  216 (4 bytes): ActionOnExitSafepointSupport.actionTL = (int) 0 (0x00000000)
  220 (4 bytes): ActionOnTransitionToJavaSupport.actionTL = (int) 0 (0x00000000)
  224 (4 bytes): ImplicitExceptions.implicitExceptionsAreFatal = (int) 0 (0x00000000)
  228 (4 bytes): StackOverflowCheckImpl.yellowZoneStateTL = (int) 2130640638 (0x7efefefe)
  232 (4 bytes): StatusSupport.safepointBehaviorTL = (int) 1 (0x00000001)
  236 (4 bytes): ThreadingSupportImpl.currentPauseDepth = (int) 0 (0x00000000)
  
No VMOperation in progress

The 15 most recent VM operation status changes (oldest first):
  1660934988210 - Started Garbage collection (safepoint: true, queueingThread: 0x0000000006030a40, executingThread: 0x0000000006030a40, safepointId: 1)
  1660934988220 - Finished Garbage collection (safepoint: true, queueingThread: 0x0000000006030a40, executingThread: 0x0000000006030a40, safepointId: 1)
  
Counters:
  
Java frame anchors for the failing thread 0x0000000006030a40:
  Anchor 0x00007ffdfa892100 LastJavaSP 0x00007ffdfa8920f0 LastJavaIP 0x00000000006bf6af
  
Stacktrace for the failing thread 0x0000000006030a40:
  SP 0x00007ffdfa891f90 IP 0x00007f3e9b92cef4  IP is not within Java code. Trying frame anchor of last Java frame instead.
  SP 0x00007ffdfa8920f0 IP 0x00000000006bf6af  [image code] com.oracle.svm.core.posix.headers.Pwd.getpwuid(Pwd.java)
  SP 0x00007ffdfa8920f0 IP 0x00000000006bf6af  [image code] com.oracle.svm.core.posix.PosixSystemPropertiesSupport.userHomeValue(PosixSystemPropertiesSupport.java:52)
  SP 0x00007ffdfa892130 IP 0x00000000006afb26  [image code] com.oracle.svm.core.jdk.SystemPropertiesSupport.userHome(SystemPropertiesSupport.java:240)
  SP 0x00007ffdfa892130 IP 0x00000000006afb26  [image code] com.oracle.svm.core.jdk.SystemPropertiesSupport$$Lambda$c08be315aa20ccffc6d99c8ceeebd4e4a45b68c0.get(Unknown Source)
  SP 0x00007ffdfa892150 IP 0x00000000006b01bf  [image code] com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
  SP 0x00007ffdfa892190 IP 0x00000000006afe9d  [image code] com.oracle.svm.core.jdk.SystemPropertiesSupport.ensureFullyInitialized(SystemPropertiesSupport.java:148)
  SP 0x00007ffdfa8921c0 IP 0x00000000012c7c9d  [image code] com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperties(SystemPropertiesSupport.java:164)
  SP 0x00007ffdfa8921c0 IP 0x00000000012c7c9d  [image code] java.lang.System.getProperties(System.java:301)
  SP 0x00007ffdfa8921c0 IP 0x00000000012c7c9d  [image code] sun.security.action.GetPropertyAction.privilegedGetProperties(GetPropertyAction.java:148)
  SP 0x00007ffdfa8921c0 IP 0x00000000012c7c9d  [image code] java.util.TimeZone.setDefaultZone(TimeZone.java:663)
  SP 0x00007ffdfa892210 IP 0x00000000012c6fa7  [image code] java.util.TimeZone.getDefaultRef(TimeZone.java:653)
  SP 0x00007ffdfa892210 IP 0x00000000012c6fa7  [image code] java.util.TimeZone.getDefault(TimeZone.java:642)
  SP 0x00007ffdfa892220 IP 0x0000000001216d08  [image code] java.util.Calendar.defaultTimeZone(Calendar.java:1679)
  SP 0x00007ffdfa892240 IP 0x00000000012179eb  [image code] java.util.Calendar.getInstance(Calendar.java:1660)
  SP 0x00007ffdfa892260 IP 0x000000000115aca8  [image code] java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
  SP 0x00007ffdfa892280 IP 0x0000000001157908  [image code] java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
  SP 0x00007ffdfa8922b0 IP 0x000000000061f97b  [image code] com.fasterxml.jackson.databind.util.StdDateFormat.<clinit>(StdDateFormat.java:106)
  SP 0x00007ffdfa8922f0 IP 0x000000000066590b  [image code] com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:367)
  SP 0x00007ffdfa892300 IP 0x0000000000664ab1  [image code] com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:283)
  SP 0x00007ffdfa8924c0 IP 0x0000000000490653  [image code] com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:359)
  SP 0x00007ffdfa892520 IP 0x000000000066590b  [image code] com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:367)
  SP 0x00007ffdfa892530 IP 0x0000000000664ab1  [image code] com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:283)
  SP 0x00007ffdfa8926f0 IP 0x0000000000dfabe5  [image code] io.seqera.tower.JSON.<init>(JSON.java:17)
  SP 0x00007ffdfa892720 IP 0x0000000000df26cc  [image code] io.seqera.tower.ApiClient.<init>(ApiClient.java:88)
  SP 0x00007ffdfa892750 IP 0x0000000000e2e2fc  [image code] io.seqera.tower.cli.commands.AbstractApiCmd$1.<init>(AbstractApiCmd.java:118)
  SP 0x00007ffdfa892750 IP 0x0000000000e2e2fc  [image code] io.seqera.tower.cli.commands.AbstractApiCmd.buildApiClient(AbstractApiCmd.java:118)
  SP 0x00007ffdfa892750 IP 0x0000000000e2e2fc  [image code] io.seqera.tower.cli.commands.AbstractApiCmd.api(AbstractApiCmd.java:92)
  SP 0x00007ffdfa892790 IP 0x0000000000e545b0  [image code] io.seqera.tower.cli.commands.runs.ListCmd.exec(ListCmd.java:46)
  SP 0x00007ffdfa8927d0 IP 0x0000000000e2f072  [image code] io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:373)
  SP 0x00007ffdfa892810 IP 0x0000000000e2f293  [image code] io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:54)
  SP 0x00007ffdfa892820 IP 0x00000000017e74fa  [image code] picocli.CommandLine.executeUserObject(CommandLine.java:1953)
  SP 0x00007ffdfa892870 IP 0x00000000017e1191  [image code] picocli.CommandLine.access$1300(CommandLine.java:145)
  SP 0x00007ffdfa892870 IP 0x00000000017e1191  [image code] picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
  SP 0x00007ffdfa8928a0 IP 0x00000000017e15a8  [image code] picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
  SP 0x00007ffdfa8928b0 IP 0x000000000171601f  [image code] picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
  SP 0x00007ffdfa8928b0 IP 0x000000000171601f  [image code] picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
  SP 0x00007ffdfa8928e0 IP 0x00000000017e66c9  [image code] picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
  SP 0x00007ffdfa8928e0 IP 0x00000000017e66c9  [image code] picocli.CommandLine.execute(CommandLine.java:2078)
  SP 0x00007ffdfa892920 IP 0x0000000000e2d7d6  [image code] io.seqera.tower.cli.Tower.main(Tower.java:89)
  SP 0x00007ffdfa892940 IP 0x0000000000651ba5  [image code] com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:150)
  SP 0x00007ffdfa892940 IP 0x0000000000651ba5  [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
  SP 0x00007ffdfa892970 IP 0x00000000006752fd  [image code] com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(IsolateEnterStub.java:0)
  
VM mutexes:
  mutex "referencePendingList" is unlocked.
  mutex "thread" is unlocked.
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  
Heap settings and statistics:
  Supports isolates: true
  Heap base: 0x00007f3ea2600000
  Object reference size: 8
  Aligned chunk size: 1048576
  Incremental collections: 1
  Complete collections: 1
  
Native image heap boundaries:
  ReadOnly Primitives: 0x00007f3ea2701028 - 0x00007f3ea2b8a100
  ReadOnly References: 0x00007f3ea2b8a100 - 0x00007f3ea2f159c8
  ReadOnly Relocatables: 0x00007f3ea2f16000 - 0x00007f3ea315b490
  Writable Primitives: 0x00007f3ea315c000 - 0x00007f3ea36bf130
  Writable References: 0x00007f3ea36bf130 - 0x00007f3ea4614848
  Writable Huge: 0x00007f3ea4700030 - 0x00007f3ea475b930
  ReadOnly Huge: 0x00007f3ea475c030 - 0x00007f3ea4d85b30

Heap:
  Young generation: 
    Eden: 
      edenSpace:
        aligned: 0/0 unaligned: 0/0
    Survivors: 
      Survivor-1 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-1 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 To:
        aligned: 0/0 unaligned: 0/0
  Old generation: 
    oldFromSpace:
      aligned: 6291456/6 unaligned: 0/0
      aligned chunks:
        0x00007f3ea2400000 (0x00007f3ea2401028-0x00007f3ea24fff58)
        0x00007f3ea2200000 (0x00007f3ea2201028-0x00007f3ea22ffef8)
        0x00007f3ea2000000 (0x00007f3ea2001028-0x00007f3ea2100000)
        0x00007f3ea1e00000 (0x00007f3ea1e01028-0x00007f3ea1efffd0)
        0x00007f3ea1c00000 (0x00007f3ea1c01028-0x00007f3ea1cfffe8)
        0x00007f3ea1a00000 (0x00007f3ea1a01028-0x00007f3ea1a7ef68)
    oldToSpace:
      aligned: 0/0 unaligned: 0/0
    
  Unused:
    aligned: 35651584/34
    aligned chunks:
      0x00007f3ea0800000 (0x00007f3ea0801028-0x00007f3ea0801028)
      0x00007f3ea0600000 (0x00007f3ea0601028-0x00007f3ea0601028)
      0x00007f3ea0400000 (0x00007f3ea0401028-0x00007f3ea0401028)
      0x00007f3ea0200000 (0x00007f3ea0201028-0x00007f3ea0201028)
      0x00007f3ea0000000 (0x00007f3ea0001028-0x00007f3ea0001028)
      0x00007f3e9fe00000 (0x00007f3e9fe01028-0x00007f3e9fe01028)
      0x00007f3e9fc00000 (0x00007f3e9fc01028-0x00007f3e9fc01028)
      0x00007f3e9fa00000 (0x00007f3e9fa01028-0x00007f3e9fa01028)
      0x00007f3e9f800000 (0x00007f3e9f801028-0x00007f3e9f801028)
      0x00007f3e9f600000 (0x00007f3e9f601028-0x00007f3e9f601028)
      0x00007f3e9f400000 (0x00007f3e9f401028-0x00007f3e9f401028)
      0x00007f3e9f200000 (0x00007f3e9f201028-0x00007f3e9f201028)
      0x00007f3e9f000000 (0x00007f3e9f001028-0x00007f3e9f001028)
      0x00007f3e9ee00000 (0x00007f3e9ee01028-0x00007f3e9ee01028)
      0x00007f3e9ec00000 (0x00007f3e9ec01028-0x00007f3e9ec01028)
      0x00007f3e9ea00000 (0x00007f3e9ea01028-0x00007f3e9ea01028)
      0x00007f3e9e800000 (0x00007f3e9e801028-0x00007f3e9e801028)
      0x00007f3e9e600000 (0x00007f3e9e601028-0x00007f3e9e601028)
      0x00007f3e9e400000 (0x00007f3e9e401028-0x00007f3e9e401028)
      0x00007f3e9e200000 (0x00007f3e9e201028-0x00007f3e9e201028)
      0x00007f3e9e000000 (0x00007f3e9e001028-0x00007f3e9e001028)
      0x00007f3e9de00000 (0x00007f3e9de01028-0x00007f3e9de01028)
      0x00007f3e9dc00000 (0x00007f3e9dc01028-0x00007f3e9dc01028)
      0x00007f3e9da00000 (0x00007f3e9da01028-0x00007f3e9da01028)
      0x00007f3e9d800000 (0x00007f3e9d801028-0x00007f3e9d801028)
      0x00007f3e9d600000 (0x00007f3e9d601028-0x00007f3e9d601028)
      0x00007f3e9d400000 (0x00007f3e9d401028-0x00007f3e9d401028)
      0x00007f3e9d200000 (0x00007f3e9d201028-0x00007f3e9d201028)
      0x00007f3e9d000000 (0x00007f3e9d001028-0x00007f3e9d001028)
      0x00007f3e9ce00000 (0x00007f3e9ce01028-0x00007f3e9ce01028)
      0x00007f3e9cc00000 (0x00007f3e9cc01028-0x00007f3e9cc01028)
      0x00007f3e9ca00000 (0x00007f3e9ca01028-0x00007f3e9ca01028)
      0x00007f3e9c800000 (0x00007f3e9c801028-0x00007f3e9c801028)
      0x00007f3e9c600000 (0x00007f3e9c601028-0x00007f3e9c601028)

Segfault detected, aborting process. Use runtime option -R:-InstallSegfaultHandler if you don't want to use SubstrateSegfaultHandler.

**Comment by robAndrewCarter** [comment]
Likewise over here. The same thing happened to me with v0.6.2 as well.
