### ISSUE TITLE
Allow to use secrets when at `launch` and pipeline creation

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#275]
Proposed commands:
```
tw pipelines add -n pipename ... --user-secrets sec1,sec2 --workspace-secrets wssec01,wsec02
tw launch pipename --user-secrets sec1,sec2 --workspace-secrets wssec01,wsec02
```

On launching a launchpad pipeline if `--user-secrets` and `--workspace-secrets` are not defined the ones from the pipeline will be used.

**Comment by BrunoGrandePhD** [comment]
Hey @jordeu! I just wanted to +1 this feature request, as we just ran into this limitation with the Tower CLI. Thanks!

**Comment by jordeu** [comment]
@BrunoGrandePhD test the new release v0.7.1 that is adding support for this.

**Comment by BrunoGrandePhD** [comment]
Thanks, @jordeu! We'll test this soon and report back if we find any unexpected behaviors.
