### ISSUE TITLE
Add resource label support

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#284]
Be nice to be able to automate the addition of resource labels via the CLI. At the moment, we can create a fully functional CE via the CLI but then have to clone it to manually add resource labels.

**Comment by jordeu** [comment]
Duplicated or complementary of #230. Maybe #230 is missing the CE part.

**Comment by jordeu** [comment]
Closing this in favor of issue #230. Please check that issue and comment if it's not going to support all your use cases once implemented.
