### ISSUE TITLE
Don't use the version at the released binaries

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#287]
Currently the URLs to download `tw` are like:

`https://github.com/seqeralabs/tower-cli/releases/download/v0.7.2/tw-0.7.2-linux-x86_64`

If we remove the version from the file name like:

`https://github.com/seqeralabs/tower-cli/releases/download/v0.7.2/tw-linux-x86_64`

Then will be possible to have a single URL that always download latest version:

`https://github.com/seqeralabs/tower-cli/releases/latest/download/tw-linux-x86_64`

**Comment by gwright99** [comment]
I assume it will still be possible to download a specific version of tw after this change? 
It is only the `/latest` URL that will be subject to rolling resolution?

**Comment by jordeu** [comment]
> I assume it will still be possible to download a specific version of tw after this change? It is only the `/latest` URL that will be subject to rolling resolution?

yes

**Comment by ewels** [comment]
Will this be applied retrospectively, or will existing URLs be stable?

As long as it's only going forward I think it should be fine. We bump the `tw` version that the action uses manually so it's just a case of updating the URL as well. Code [here](https://github.com/seqeralabs/action-tower-launch/blob/8ff078c8133a8ad2145a96752688a990198d6529/Dockerfile#L7):

```Dockerfile
RUN curl -L https://github.com/seqeralabs/tower-cli/releases/download/v${TOWER_CLI_VERSION}/tw-${TOWER_CLI_VERSION}-linux-x86_64 > tw
```

**Comment by jordeu** [comment]
Only going forward
