### ISSUE TITLE
bioconda release?

### ISSUE THREAD

**Issue by nick-youngblut** [seqeralabs/tower-cli#293]
Are there any plans to create a bioconda recipe for `tw`?

**Comment by pditommaso** [comment]
That sounds like a nice idea! you may want to [submit a PR](https://github.com/bioconda/bioconda-recipes) for it!

**Comment by nick-youngblut** [comment]
OK. I didn't want to create a recipe if the `tower-cli` developers wanted to maintain one themselves.

**Comment by drpatelh** [comment]
@adamrtalbot added this in https://github.com/bioconda/bioconda-recipes/pull/41629 🚀
