### ISSUE TITLE
Add ability to update the name of some entities

### ISSUE THREAD

**Issue by tcrespog** [seqeralabs/tower-cli#303]
In the near future, Tower will support editing the name of the following entities:
-  [x] Organizations
- [x] Workspaces
- [x] Pipelines
- [x] Actions
- [x] Compute environments

Ideally, the CLI would support those too. The compute environment requires an update action implemented from scratch.

**Comment by jordeu** [comment]
I understand that this is still not possible. I label this with "on hold" until this is possible at Tower API side.

**Comment by jordeu** [comment]
I've seen that we already have the "need_backend_change" label, I'll label like this until it's ready.
