### ISSUE TITLE
Sign binary with Apple developer certificate

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-cli#318]
The binary tool compiled for macOS should be signed with the Apple developer certificate. 

The signing process is described [here](https://chat.openai.com/share/65302eca-5d3e-439b-bb00-5d3a9c778b02). 

More context about the developer certificate [here](https://developer.apple.com/support/certificates/).

**Comment by jason-seqera** [comment]
Just to elaborate, the value in this is that for a signed binary, the user doesn't need to go into System Settings, then scroll through Privacy & Security to find and click an Allow button for the binary.

**Comment by pditommaso** [comment]
Sure.

**Comment by pditommaso** [comment]
I think this requires Seqera to enrol for the [Apple developer program](https://developer.apple.com/programs/). @jordigg can you please help us on this?

**Comment by jordeu** [comment]
Useful [post](https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions) for adding the codesign after as a github action after the binary is created https://github.com/seqeralabs/tower-cli/blob/a93504e579878c23412d1fe16f2de5f8e1153840/.github/workflows/build.yml#L121

**Comment by jordigg** [comment]
I'm ooo until the 27th. An Apple Developer account will be required, there is a small ($99 fee/year) I think.
We need to make sure the account where the certificate is managed is shared with additional people. Ideally the certificate is generated under a shared account or renewing it will be a pain.

Do we need another one for Windows? That would require a code-signing certificate from Godaddy for example, that will require a verification process through the "office phone" which must be a landline...

**Comment by pditommaso** [comment]
@jordigg any chance to move forward with the Apple dev cert?

**Comment by jordigg** [comment]
@pditommaso I have registered for a Developer account with Apple this morning. I'm waiting for the account to be approved.
They need to review the "legal" side of the entity. @evanfloden was added as "approver" as well.

I'll update as soon as we have it and I'll take care of paying the $99 fee.

**Comment by pditommaso** [comment]
Thanks

**Comment by jordigg** [comment]
We finally got the account.
I have invited @pditommaso and @evanfloden and @swampie as Admins.
Those who also need access can request so via a [IT Ticket](https://help.portal.seqera.io/servicedesk/customer/portal/2/group/3/create/10).
