### ISSUE TITLE
ERROR: Pipeline 'null' not found

### ISSUE THREAD

**Issue by jason-seqera** [seqeralabs/tower-cli#319]
When running `tw pipelines [name]`, if `[name]` does not exist, the error message is (in red):

```
ERROR: Pipeline 'null' not found
```

A friendlier message, such as _Could not find [name] pipeline_, might be helpful. A user might not know what `null` refers to in this context.

This originates here: https://github.com/seqeralabs/tower-cli/blob/c798af733861097803a84eec6779b3e3859ec7be/src/main/java/io/seqera/tower/cli/commands/LaunchCmd.java#L147

**Comment by JaimeSeqLabs** [comment]
Hi @jason-seqera,
I think [this](https://github.com/seqeralabs/tower-cli/commit/c798af733861097803a84eec6779b3e3859ec7be) solved the issue
