### ISSUE TITLE
add silicon m1/m2 target to the release artifacts

### ISSUE THREAD

**Issue by swampie** [seqeralabs/tower-cli#328]
Currently intel is the only target for OSX systems
Add silicon M1/M2 to the release targets

https://github.com/oracle/graal/issues/2666

**Comment by pditommaso** [comment]
There's no Silicon-based VM runner in GH

**Comment by jordeu** [comment]
There is this option https://tart.run/integrations/github-actions/

Or to have a mini M2 at the office setup as a self-hosted runner

**Comment by pditommaso** [comment]
Is it possible to have builds using with both provisioned and self-hosted runners?

**Comment by alvaromartmart** [comment]
I'm tracking this issue, will ping you if there are any updates: https://github.com/github/roadmap/issues/528.

In the meantime, it's always possible to build the binary locally and manually add it to the Github release artifacts.

**Comment by jordeu** [comment]
> Is it possible to have builds using with both provisioned and self-hosted runners?

I think it's possible

**Comment by alvaromartmart** [comment]
Good news! https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by pditommaso** [comment]
Let's do it NOW 

<img src="https://media1.giphy.com/media/bky50dwwRsYBrsiKJU/giphy.gif"/>

**Comment by pditommaso** [comment]
So simple?! 

https://github.com/seqeralabs/wavelit/commit/28abd8087f3e4176e8f8d08f79fc747818eac0e1

**Comment by pditommaso** [comment]
Nahhh, still getting `compiler: cc (apple, x86_64, 14.0.3)`


`

**Comment by pditommaso** [comment]
It's happening! `cc (apple, arm64, 14.0.3)`

**Comment by alvaromartmart** [comment]
![Screenshot 2023-10-03 at 08 13 54](https://github.com/seqeralabs/tower-cli/assets/18287793/c4cb3cf9-7a33-40c7-a37f-fc1f6ca284ed)

wow, it takes half the time to build
