### ISSUE TITLE
Tower API couldn't be called for workflow submission

### ISSUE THREAD

**Issue by Truongphi20** [seqeralabs/tower-cli#331]
I have a pipeline and have run it successfully many times before. I always use Nextflow Tower in other to monitor my pipeline. However, today I got an error engaging to Tower API, which couldn't be called when running the pipeline.
```
N E X T F L O W  ~  version 23.04.2
Launching `nana/main.nf` [clever_meninsky] DSL2 - revision: a818d67225
Unexpected response for request https://api.tower.nf/trace/create?workspaceId=155308103402063
```
I suppose that could be the maintenance of Nextflow Tower, hope to get some notice.

**Comment by minhtrung1997** [comment]
Today, when I rerun pipeline for comapny, I also meet this errors🥺

**Comment by cbr7** [comment]
@Truongphi20 @minhtrung1997 was the error persistent or was it only happening sometimes? Did you try executing any other pipelines to see if the error is pipeline specific or more systemic in nature? Also it would be good to know if you tried to execute the pipeline from tower UI after it failed from CLI? And if so was the execution successful in that case?

**Comment by Truongphi20** [comment]
I definitely confirmed that it happens every time the pipeline is started. I only run it on CLI

**Comment by minhtrung1997** [comment]
Use GUI, also failed:
![image](https://github.com/seqeralabs/tower-cli/assets/52932655/a813ffe1-a622-43f5-9d2d-7be61b33c2ed)

Tower agent gets stuck at API
![image](https://github.com/seqeralabs/tower-cli/assets/52932655/4276d03b-7c3c-4d38-86b7-be97d5851bad)

**Comment by minhtrung1997** [comment]
By the way, 3h later, it work :+1: 
![image](https://github.com/seqeralabs/tower-cli/assets/52932655/ed784853-27c9-4c38-84a7-406d3be04262)

**Comment by Truongphikt** [comment]
Now, It also works for me too. 👍

**Comment by Truongphi20** [comment]
Now, It also works for me too. 👍

**Comment by jordeu** [comment]
Closing; not directly related to Tower CLI and seems a transient connectivity issue that was somehow solved.
