### ISSUE TITLE
Unsupported SPOT_PRICE_CAPACITY_OPTIMIZED allocation strategy.

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#332]
The new AWS Batch forge allocation strategy `SPOT_PRICE_CAPACITY_OPTIMIZED` is not supported.
 
It is not possible to create a CE using this strategy and if you try to do a `tw compute-envs view ...` of a compute environment that uses this strategy you always get a "connection error" message.

**Comment by gwright99** [comment]
@JaimeSeqLabs for clarity are you saying:

1. This should have already been working in v0.8, or
2. You've ported in functionality and it will be available in v0.9? (_I assume this one_).
