### ISSUE TITLE
Manage datasets

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#35]
`towr datasets list -f <search>`
`towr datasets create -n ...`
`towr datasets delete -n ...`
`towr datasets update -n ...` (this allows to add a new version)
`towr datasets view -n ...` 
`towr datasets download -n ...` (this allows to download the dataset)
`towr datasets url -n ...` (get the dataset url)

**Comment by jordeu** [comment]
This needs to first release a new SDK with the datasets endpoint unhidden using this PR https://github.com/seqeralabs/nf-tower-cloud/pull/2240

**Comment by swampie** [comment]
I am moving this to 0.5

**Comment by jordeu** [comment]
The SDK `tower-java-sdk:1.1.0` with datasets support has been released.

**Comment by jordeu** [comment]
Related PR to make this API public when we verify that is working:
https://github.com/seqeralabs/nf-tower-cloud/pull/2240

**Comment by grananda** [comment]
Missing a `versions` command here. Can it be added?

**Comment by grananda** [comment]
I believe we should add the versions along with the `view` command as an extra option `--versions`.

**Comment by jordeu** [comment]
Yes I'd put it inside `view` but maybe as a subcommand like we are doing with the `tw runs view -i ... tasks` subcommand. More or less is the same pattern.

**Comment by grananda** [comment]
When it comes to the download URL, I thought about returning the latest version URL unless the user specifies the version number. Any ideas?

**Comment by jordeu** [comment]
Yes, it make sense to show the latest unless version is set.

**Comment by jordeu** [comment]
I've released a new snapshot version of the SDK fixing the token problem:

You should be able to use it updating your gradle build config like this:
```
diff --git a/build.gradle b/build.gradle
index 99bd76b..e89c48f 100644
--- a/build.gradle
+++ b/build.gradle
@@ -8,7 +8,7 @@ plugins {
 
 repositories {
     mavenCentral()
-    maven { url = "https://s3-eu-west-1.amazonaws.com/maven.seqera.io/releases" }
+    maven { url = "https://s3-eu-west-1.amazonaws.com/maven.seqera.io/snapshots" }
 }
 
 dependencies {
@@ -16,7 +16,7 @@ dependencies {
     implementation 'org.slf4j:slf4j-api:1.7.32'
     implementation 'ch.qos.logback:logback-core:1.2.6'
     implementation 'ch.qos.logback:logback-classic:1.2.6'
-    implementation 'io.seqera:tower-java-sdk:1.1.0'
+    implementation 'io.seqera:tower-java-sdk:1.2.0-SNAPSHOT'
     implementation 'info.picocli:picocli:4.6.1'
     annotationProcessor 'info.picocli:picocli-codegen:4.6.1'
```

I'll keep it as a snapshot until we are near to finish this and then I'll do a `1.2.0` release before merging this to master.
