### ISSUE TITLE
Add Workspace name in JSON from tw runs dump

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#355]
We are developing a MultiQC module that is able to scrape the output of `tw runs dump` in order to aggregate metrics into a single report across runs. It would be useful to be able to get the Workspace name directly from the JSON files that we can add to the General Stats table to clarify where the run was executed, especially if collating runs across Workspaces in the Report. 

At the moment, only the `workspaceId` is reported in `workflow-launch.json`.

See https://github.com/ewels/MultiQC/pull/2151#issuecomment-1788912050

**Comment by JaimeSeqLabs** [comment]
Closed in #364
