### ISSUE TITLE
Add Run labels in JSON from tw runs dump

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#357]
We are developing a MultiQC module that is able to scrape the output of `tw runs dump` in order to aggregate metrics into a single report across runs. It would be useful to be able to get run labels directly from the JSON files that we can add to the report. We can then add these to the report to help with filtering / sorting etc.

See https://github.com/ewels/MultiQC/pull/2151#issuecomment-1788912050

**Comment by swampie** [comment]
@drpatelh resource labels or simple labels or both?

**Comment by drpatelh** [comment]
Both please 🙏🏽 For simple labels we can decorate the MultiQC report for filtering and for resource labels we can try to set something up that scrapes costs from Cost Explorer automatically per run.

**Comment by JaimeSeqLabs** [comment]
Closed in #364
