### ISSUE TITLE
Improve runs view subcommand

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#36]
Currently we are only showing few information about one run. Add different flags, one for each subsection an show only selected subsections. If non is provided only the `--general` section is shown.

Example:
`towr runs view -i <run_id> --general --config --params`

The sections will try to mimic the web interface if possible.

Available sections:

- ~`--general`~
- `--config`
- `--params`
- `--command`
- ~`--status`~
- `--processes`
- `--stats`
- `--load`
- `--utilization`
- `--metrics` (show the info using a table. If this is too much info consider to split in different sections: `--memory` `--cpu` ...)

Tasks, logs/downloads and reports are not consider in this issue.

**Comment by swampie** [comment]
@grananda use the pretty print for params

**Comment by swampie** [comment]
-- metrics is converted to a command
