### ISSUE TITLE
What does "Infrastructure as Code" mean within the Tower CLI context?

### ISSUE THREAD

**Issue by max-l-weaver** [seqeralabs/tower-cli#385]
Ok I'm not going to lie, when I first saw the following statement in your documentation I got quite excited:

> Infrastructure as Code: All Tower resources including Pipelines and Compute Environments can be described in a declarative manner. This allows a complete definition of an analysis environment that can be versioned and treated as code. It greatly simplifies sharing and re-use of configuration as well as routine administration.

As someone who comes from Terraform and is eagerly looking at similar ways to deploy Nextflow Tower resources without scripting, I assumed this meant I could declare a resource in the same way I would in Terraform (allbeit using json instead of hcl) and use the tw create resources from said files. What I _think_ it means though is that someone can create resources, output the state of these resources as json via the tw cli and then store these in version control. I'd like to know how this is IaC, as it still requires manually creating resources via tw commands.

If this is the case, I think saying that "All Tower resources including Pipelines and Compute Environments can be described in a declarative manner" is a bit disingenuous. At the very least there should be further documentation and clarification on what this means and how you declare Nextflow Tower resources decleratively.

Or perhaps I'm completely wrong and in which case would like a bit more documentation on this please.

**Comment by bentsherman** [comment]
IaC doesn't necessarily mean Terraform in this context, just that Platform resources like workspaces, users, compute environments, etc can be created programmatically through the CLI rather than through the web interface. So the CLI isn't really IaC out of the box but the foundation for IaC.

I believe [seqera-kit](https://github.com/seqeralabs/seqera-kit) implements much of this automation, and it uses the Seqera CLI under the hood

**Comment by max-l-weaver** [comment]
thanks for the clarification @bentsherman .

Seeing that statement I thought it meant I could declare Tower resources as something like json and then use the tw cli to apply them.

I'll take a look at the seqera kit
