### ISSUE TITLE
Add support for AWS CodeCommit credentials

### ISSUE THREAD

**Issue by ejseqera** [seqeralabs/tower-cli#387]
Add support for CodeCommit credentials provider through the CLI to be able to create/delete/update:
```bash
tw credentials add codecommit
```
```bash
tw credentials update codecommit
```

With the following options, ideally:
```console
Options:
* -n, --name=<name>                       Credentials name.
  -w, --workspace=<workspace>             Workspace numeric identifier (TOWER_WORKSPACE_ID as default) or workspace reference as OrganizationName/WorkspaceName
      --overwrite                         Overwrite the credentials if it already exists.
  -a, --access-key=<accessKey>            The AWS access key of IAM account to access target repository.
  -s, --secret-key=<secretKey>
  -u, --repository-url=<repositoryBaseURL>
  ```

**Comment by robnewman** [comment]
> After careful consideration, we have made the decision to close new customer access to AWS CodeCommit, effective July 25, 2024. AWS CodeCommit existing customers can continue to use the service as normal. AWS continues to invest in security, availability, and performance improvements for AWS CodeCommit, but we do not plan to introduce new features.

[Source](https://aws.amazon.com/blogs/devops/how-to-migrate-your-aws-codecommit-repository-to-another-git-provider/)
