### ISSUE TITLE
Tower API version error when running tw info

### ISSUE THREAD

**Issue by ejseqera** [seqeralabs/tower-cli#392]
Running `v0.9.2` of the CLI on MacOS returns the following when running the info command:
```console
$ tw info

    Details
    -------------------------+----------------------
     Tower API endpoint      | https://api.tower.nf
     Tower API version       | 1.9.0
     Tower version           | 24.1.0-cycle10
     CLI version             | 0.9.2 (39a2ec6)
     CLI minimum API version | 1.15
     Authenticated user      | esha-joshi

    System health status
    ---------------------------------------+--------
     Remote API server connection check    | OK
     Tower API version check               | FAILED
     Authentication API credential's token | OK

    Tower API version is 1.9.0 while the minimum required version to be fully compatible is 1.15
```
This doesn't actually interfere with the CLI functionality but would be good to know - why we we are seeing this and are we supposed to be able configure the Tower API version being used?

**Comment by jordeu** [comment]
You cannot configure the Tower API version. This is just a warning and means you are using the CLI with an old Tower API, and some new CLI features may not work. 

But what is happening now is that there is a glitch on the Tower side, which is reporting the wrong API version. I've alerted the platform team, and they will fix it.

Thanks for reporting.

**Comment by ejseqera** [comment]
Right, I figured. Thanks for the explanation and escalating to the Platform team, Jordi.

**Comment by jordeu** [comment]
The problem with the API version has been fixed. I am closing this issue.

**Comment by gwright99** [comment]
@jordeu @ejseqera 

"It's ok, just a little bit old" isn't the first thing that comes to mind when I see `FAILED`. 

Wouldn't it be better to have a more user-friendly/self-describing message like "_tw upgrade advised_" or "_Not all features available_"?

**Comment by jordeu** [comment]
@gwright99 you're right maybe we can improve the message. Feel free to open an issue/PR with a proposal.
https://github.com/seqeralabs/tower-cli/blob/2d10b5b9ab61195b685ff2f809240d88864375be/src/main/java/io/seqera/tower/cli/responses/InfoResponse.java#L76
