### ISSUE TITLE
ERROR: A label with name 'x' already exists for workspace 'Altos_Labs_Inc'

### ISSUE THREAD

**Issue by millerh1** [seqeralabs/tower-cli#397]
Whenever I am attempting to run something like the following:

```shell
tw launch FetchNGS_NFcore --params-file fetchngs/fetchngs_tower_params.3.json --config ../src/fetchngs_nextflow.config --compute-env xyz --labels x,y
```

I get this error:

```shell
ERROR: A label with name 'x' already exists for workspace 'Altos_Labs_Inc'
```

Is there a way to label these pipeline runs even if the label already exists? From the tower GUI, this is possible.

**Comment by ShahzebMahmood** [comment]
# Sharing further details

This is a Seqera Platform User

Tomas mentions
> Based on the tower-cli output shared by the user, my bet is that the CLI verifies first if any of the labels to attach exists in the workspace (`GET ... /api/labels` call), but it only lists the first page of 10 labels while there are 75 total labels: the label is not present on that page, so the CLI assumes that it does not exist and tries to create it again (`POST ... /api/labels` call) resulting in the name uniqueness error. We have to fix it on the CLI side.

I was not able able to replicate the specific error the user has been experiencing.

**Comment by endre-seqera** [comment]
Quick update, a fix for this was merged: https://github.com/seqeralabs/platform/pull/6982

**Comment by millerh1** [comment]
I'm still getting this error. Do I need to ask our IT folks to update
something for tower?

Best,
Henry

**Comment by ShahzebMahmood** [comment]
Hey, @millerh1 I have sent you a response regarding the above question on the FD ticket.

**Comment by millerh1** [comment]
Thanks! Looks like we need to wait for the next enterprise release. Closing now!
