### ISSUE TITLE
Conda version of CLI generates strange characters in version outputs

### ISSUE THREAD

**Issue by pinin4fjords** [seqeralabs/tower-cli#404]
```
$ tw --version 2>&1 > foo.txt
$ vim foo.txt
^[[33mTower CLI version 0.9.2 (build 39a2ec6)^[[39m^[[0m
```

**Comment by jordeu** [comment]
These are the "colours" ANSI codes. But this does not happen in Linux because redirection is automatically detected, and then "colours" are disabled.

Where are you running this?

**Comment by pinin4fjords** [comment]
Actually this was Linux (GitPod)

**Comment by jordeu** [comment]
Most likely, GitPod is using some web console that makes the automatic detection fail. I guess that if you run this in a Nextflow pipeline, the automatic detection will not fail.

This "automatic" detection is done by Picocli library here:
https://github.com/seqeralabs/tower-cli/blob/e1e440f820780d9fb72ff6cab2c1d75e9a7f4036/src/main/java/io/seqera/tower/cli/responses/Response.java#L45


You can explicitly remove ANSI colours by setting the `NO_COLOR` environment variable.

Example:
```bash
NO_COLOR=true tw --version 2>&1 > foo.txt
```

**Comment by pinin4fjords** [comment]
Yes, that works great, thank you.
