### ISSUE TITLE
[Data explorer] Add delete custom data links support to CLI

### ISSUE THREAD

**Issue by weronikasosnowskaseqera** [seqeralabs/tower-cli#407]
Implement deleting custom data link in CLI

```bash
tw data-links delete --datalink=<datalinkId> --workspace=<workspaceId>   # delete a datalink in a workspace
```

**Comment by gwright99** [comment]
Is this going to make it into [USAGE.md](https://github.com/seqeralabs/tower-cli/blob/master/USAGE.md)?

**Comment by weronikasosnowskaseqera** [comment]
@gwright99 There is a ready PR with listing buckets, listing content from bucket and create/update/delete custom data links https://github.com/seqeralabs/tower-cli/pull/411. You can check It out and test.

**Comment by robnewman** [comment]
> Is this going to make it into [USAGE.md](https://github.com/seqeralabs/tower-cli/blob/master/USAGE.md)? (_data link examples in general, I mean_)

@gwright99 Added in https://github.com/seqeralabs/tower-cli/pull/442
