### ISSUE TITLE
Download runs files

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#41]
Download files and logs of a run:
`towr runs view -i <run_id> download --type <download_type>`

If the task id is set download task files:
`towr runs view -i <run_id> download -t <task_id> --type <download_type>`

Possible download types:

1. `stdout` Console output
2. `stderr` Standard error output
3. `logs` Log files
4. `timeline` timeline file

**Comment by grananda** [comment]
When using the `json` option, do we wish the json to contain the file local path or the file content? IMO, I think the path could be more useful  when operating under a bash script or piped process. Any thoughts?

**Comment by jordeu** [comment]
> When using the `json` option, do we wish the json to contain the file local path or the file content? IMO, I think the path could be more useful when operating under a bash script or piped process. Any thoughts?

Are you forcing them to always give a file name? (I mean instead of showing the content at `stdout`)

**Comment by jordeu** [comment]
For me the first version I'll go to only output the contents to `stdout` and when using the `json` output put all the content in the `json` output. 

If we, optionally, allow to store it directly into a file then the `json` view for me makes more sense that only gives you the file paths.

**Comment by grananda** [comment]
Apparently the CLI stores all the data into a temp file by default, which is why I considered it convenient to make use of that commodity.
