### ISSUE TITLE
Add compatibility flag while compiling Linux executable

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/tower-cli#412]
While testing changes related to an update of the [Workflow Automation for Nextflow Pipelines](https://seqera.io/blog/workflow-automation/), I encountered an issue which I hope will be solved by adding a compatibility flag during the compilation of the `tw` binary.

## Background
The Dockerfile which the Lambda image is generated from used this snippet to install the `tw` CLI:
```bash
RUN wget https://github.com/seqeralabs/tower-cli/releases/download/v0.9.2/tw-linux-x86_64 && \
chmod +x ./tw-linux-x86_64 && \
mv ./tw-linux-x86_64 /usr/local/bin/tw
```

The image works perfectly fine in the local testing environment but sporadically fails in the AWS Lambda environment with the following error:
```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA]. \nPlease rebuild the executable with an appropriate setting of the -march option.
```

When I delete and redeploy the lambda, the exact same code and image will successfully execute and not throw this error. 

## Hypothesis
I suspect that the x86_64 fleet AWS uses to host the lambdas are not uniform and that the error occurs when the Lambda is deployed to a too-old machine.

I know this error is **not** due to deployment on arm64 infrastructure because I tried this and get a completely different error:
```bash
Error: fork/exec ./entry_script.sh exec format error Runtime.InvalidEntrypoint
```

## Reproducibility
Since I have no control over the x86_64 AWS instance my Lambda spins up on, I do not have a bulletproof way to reproduce the problem. Thus far, I have been using IAC to rapidly spin-up/spin-down the solution and am able to generate anomalies via brute force.

## Workaround
After speaking to @JaimeSeqLabs, I was advised that using the [tw.jar](https://github.com/seqeralabs/tower-cli/releases/tag/v0.9.2) solution could help me avoid the compatibility issue due to the universality of the JVM. 

Credit where credit is due: the JVM solution seems stable thus far. The downside is that it comes with additional costs:

1. It took time to figure out how to install the JVM in a way that it could be accessed from the AWS Lambda Python runtime.
2. The inclusion of Corretto 17 bloated my container image by 500+ MB.
3. The RAM required to run the Lambda increased x10  (_the original Python app with `tw` binary successfully executes with only 128 MB RAM whereas the `.jar`-based solution only works if the Lambda is provided 1024MB_).

## Requested Remediation
As per the Lambda error message and [GraalVM docs](https://www.graalvm.org/latest/reference-manual/native-image/overview/Options/#:~:text=%2Dmarch%20%3A%20generate%20instructions%20for%20a,with%20the%20same%20CPU%20features), adding `-march=compatibility` to the compilation process could (potentially) avoid the missing CPU feature problem.

**Comment by munishchouhan** [comment]
@gwright99 @JaimeSeqLabs I have added  `-march=compatibility` in tower-cli too, which solves this same problem in wave -cli.
