### ISSUE TITLE
Add --launch-container option to `launch` command 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-cli#436]
Upcoming release of Platform is going to provide a `launchContainer` option in the launch API, that allows specifying container to be used to run the nextflow head job. 

The goal of this issue is to add support for this feature by add the `--launch-container` CLI option to the `launch` command. 

See also https://github.com/seqeralabs/platform/pull/7298

**Comment by munishchouhan** [comment]
I think it needs a new release of `io.seqera.tower:tower-java-sdk` with LuanchContainer
cc @JaimeSeqLabs @tcrespog
