### ISSUE TITLE
Release 0.9.3 for OSX x86_64 does not work

### ISSUE THREAD

**Issue by theJasonFan** [seqeralabs/tower-cli#438]
Just wanted to quickly report that the precompiled binary does not work on my intel Macbook pro

Console output:
```console
$ ./tw-osx-x86_64 -h
zsh: bad CPU type in executable: ./tw-osx-x86_64
```

On a 2019 16in Macbook Pro with a 2.6 GHz 6-Core Intel Core i7 CPU.

Thanks!

**Comment by munishchouhan** [comment]
@theJasonFan thanks for reporting the issue
please download tw-mac from here https://github.com/seqeralabs/tower-cli/actions/runs/9989837685
and try

**Comment by munishchouhan** [comment]
it will be solved in next release
