### ISSUE TITLE
Change --json flag to --output

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/tower-cli#52]
The `--json` flag allows rendering the outout as a JSON content. It may be better to use instead `--output|-o json` option so that in the future it's possible to add other formats, e.g. `text`, `csv`, etc

**Comment by abhi18av** [comment]
I think I've hit across a bug, with the assumption that `--json` is supposed to be applicable to all the (sub-)commands too

This is with `0.3` 

```
./tw compute-envs list --json
Unknown option: '--json'

Usage: tw compute-envs list [OPTIONS]

List all workspace compute environments

Options:
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
```

**Comment by grananda** [comment]
The `--output` option (formerly known as `--json)` is placed before the command and right after `./th`

`./tw --output json compute-envs list`

It applies to all subcommands but does not target specific subcommands within a long command.

**Comment by abhi18av** [comment]
Ah, I see. Thanks @grananda!

Will confirm the behavior for this later today.
