### ISSUE TITLE
Explicit error messages when 403

### ISSUE THREAD

**Issue by grananda** [seqeralabs/tower-cli#86]
# Summary 
API should report a more explicit 403 message when a resource is not compatible with the working workspace.

# Intended output
There are mainly two scenarios to contemplate here:
- A pipeline is imported into workspace 2 with a computer environment from workspace 1
- A compute-env is imported into workspace 2 with credentials set from workspace 1

For such cases, the  API should inform of such specific messages to prevent extra validations in the CLI command side.

**Comment by jordeu** [comment]
Too generic issue. We'll progressive improve error messages when available at API level.
